### ISSUE TITLE
Deleting conflicts

### ISSUE THREAD

**Issue by ycd** [psadmin-io/ioco#1]
Hey @iversond I was looking throught the code and i found a lot of unmerged conflicts. You might want to check them out.

https://github.com/psadmin-io/ioco/blob/aa811c8b51fc51d0347aa3f18706869e2f04abd6/ioco/oci.py#L30-L35
https://github.com/psadmin-io/ioco/blob/aa811c8b51fc51d0347aa3f18706869e2f04abd6/ioco/oci.py#L80-L84
https://github.com/psadmin-io/ioco/blob/aa811c8b51fc51d0347aa3f18706869e2f04abd6/ioco/oci.py#L102-L106
https://github.com/psadmin-io/ioco/blob/aa811c8b51fc51d0347aa3f18706869e2f04abd6/ioco/__main__.py#L1

**Comment by kbens** [comment]
Thanks for pointing this out. We were working off a private repo for our demo and rushed this public launch. Should be cleared up now.
